name: Python Wheels

on:
  workflow_dispatch:

  push:
    branches:
      - dev

  pull_request:
    branches:
      - master

  release:
    types:
      - published

  schedule:
    - cron: "0 0 * * 1"

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - name: Upload SDist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: photoshopapi-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os_dist.os }}-${{ matrix.os_dist.dist }}

    permissions:
      actions: read
      contents: read

    runs-on: ${{ matrix.os_dist.os }}

    strategy:
      fail-fast: false

      matrix:
        os_dist:
          - { os: ubuntu-latest, dist: cp312-manylinux_x86_64 }
          - { os: ubuntu-latest, dist: cp313-manylinux_x86_64 }
          - { os: ubuntu-latest, dist: cp314-manylinux_x86_64 }

          - { os: windows-latest, dist: cp312-win_amd64 }
          - { os: windows-latest, dist: cp313-win_amd64 }
          - { os: windows-latest, dist: cp314-win_amd64 }

          - { os: macos-latest, dist: cp312-macosx_arm64 }
          - { os: macos-latest, dist: cp313-macosx_arm64 }
          - { os: macos-latest, dist: cp314-macosx_arm64 }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup macOS dependencies
        if: matrix.os_dist.os == 'macos-latest'
        run: |
          brew install autoconf
          brew install libtool
          brew install automake

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: ${{ matrix.os_dist.os }}_wheels_vcpkg

      - name: Build Wheels
        uses: pypa/cibuildwheel@v3.3.1

        env:
          VCPKG_FEATURE_FLAGS: binarycaching
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"

          CIBW_ENVIRONMENT_LINUX: >
            VCPKG_FEATURE_FLAG="binarycaching"
            VCPKG_BINARY_SOURCES="clear;files,/output/.vcpkg-cache,readwrite"

          CC: ${{ matrix.os_dist.os == 'macos-latest' && 'clang' || 'gcc-13' }}
          CXX: ${{ matrix.os_dist.os == 'macos-latest' && 'clang++' || 'g++-13' }}

          CIBW_ARCHS: auto64
          CIBW_BUILD: ${{ matrix.os_dist.dist }}

          MACOSX_DEPLOYMENT_TARGET: "15.0"

          CIBW_BEFORE_ALL_LINUX: |
            dnf install -y zip
            dnf install -y perl-IPC-Cmd
            dnf install -y perl-core

            mkdir -p /output/.vcpkg-cache

            if [ -d /host${{ github.workspace }}/.vcpkg-cache ]; then
              cp -r /host${{ github.workspace }}/.vcpkg-cache/* /output/.vcpkg-cache/
            fi

      - name: Copy vcpkg cache (Linux only)
        if: matrix.os_dist.os == 'ubuntu-latest'
        run: |
          rm -rf ${{ steps.vcpkg-cache.outputs.path }}
          mv ./wheelhouse/.vcpkg-cache ${{ steps.vcpkg-cache.outputs.path }}

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload Wheel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: photoshopapi-${{ matrix.os_dist.os }}-${{ matrix.os_dist.dist }}
          path: wheelhouse/*.whl

  mock-release:
    name: Mock Release Verification

    needs:
      - build_wheels
      - build_sdist

    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          pattern: "*"
          merge-multiple: true

      - name: Show Files
        run: ls -R release-assets

  github-release:
    name: Upload GitHub Release Assets

    if: github.event_name == 'release' && github.event.action == 'published'

    needs:
      - build_wheels
      - build_sdist

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          pattern: "*"
          merge-multiple: true

      - name: Show Files
        run: ls -R release-assets

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/**/*.whl
            release-assets/**/*.tar.gz
